// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID        pgtype.UUID      `json:"id"`
	Type      string           `json:"type"`
	Payload   []byte           `json:"payload"`
	Enqueued  bool             `json:"enqueued"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ProgramID pgtype.UUID      `json:"program_id"`
}

type Program struct {
	ID          pgtype.UUID      `json:"id"`
	Slug        string           `json:"slug"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Type        string           `json:"type"`
	Language    string           `json:"language"`
	DurationMs  int32            `json:"duration_ms"`
	Tags        []string         `json:"tags"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
	CreatedBy   pgtype.UUID      `json:"created_by"`
	PublishedBy pgtype.UUID      `json:"published_by"`
	UpdatedBy   pgtype.UUID      `json:"updated_by"`
	DeletedBy   pgtype.UUID      `json:"deleted_by"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
