// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (type, payload, program_id)
VALUES ($1, $2, $3)
RETURNING id, type, payload, enqueued, created_at, program_id
`

type CreateOutboxEventParams struct {
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
	ProgramID pgtype.UUID `json:"program_id"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.Type, arg.Payload, arg.ProgramID)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Enqueued,
		&i.CreatedAt,
		&i.ProgramID,
	)
	return i, err
}
