// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignCategories = `-- name: AssignCategories :exec
INSERT INTO categorized_as (program_id, category_id)
VALUES ($1, unnest($2::uuid[]))
ON CONFLICT (program_id, category_id) DO NOTHING
`

type AssignCategoriesParams struct {
	ProgramID pgtype.UUID   `json:"program_id"`
	Column2   []pgtype.UUID `json:"column_2"`
}

func (q *Queries) AssignCategories(ctx context.Context, arg AssignCategoriesParams) error {
	_, err := q.db.Exec(ctx, assignCategories, arg.ProgramID, arg.Column2)
	return err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (slug, title, description, type, language, duration_ms, source_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by
`

type CreateProgramParams struct {
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Language    string      `json:"language"`
	DurationMs  int32       `json:"duration_ms"`
	SourceID    pgtype.UUID `json:"source_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.DurationMs,
		arg.SourceID,
		arg.CreatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.SourceID,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const deleteProgram = `-- name: DeleteProgram :exec
UPDATE programs
SET deleted_at = NOW(), deleted_by = $2
WHERE id = $1
`

type DeleteProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteProgram(ctx context.Context, arg DeleteProgramParams) error {
	_, err := q.db.Exec(ctx, deleteProgram, arg.ID, arg.DeletedBy)
	return err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by FROM programs WHERE id = $1
`

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.SourceID,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getProgramBySlug = `-- name: GetProgramBySlug :one
SELECT id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by FROM programs WHERE slug = $1
`

func (q *Queries) GetProgramBySlug(ctx context.Context, slug string) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramBySlug, slug)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.SourceID,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getProgramCategories = `-- name: GetProgramCategories :many
SELECT c.id, c.name, c.description FROM categories c
JOIN categorized_as ca ON c.id = ca.category_id
WHERE ca.program_id = $1
`

func (q *Queries) GetProgramCategories(ctx context.Context, programID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getProgramCategories, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by FROM programs WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Language,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.SourceID,
			&i.CreatedBy,
			&i.PublishedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProgram = `-- name: PublishProgram :one
UPDATE programs
SET published_at = NOW(), published_by = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by
`

type PublishProgramParams struct {
	ID          pgtype.UUID `json:"id"`
	PublishedBy pgtype.UUID `json:"published_by"`
}

func (q *Queries) PublishProgram(ctx context.Context, arg PublishProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, publishProgram, arg.ID, arg.PublishedBy)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.SourceID,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const removeCategories = `-- name: RemoveCategories :exec
DELETE FROM categorized_as
WHERE program_id = $1 AND category_id = ANY($2::uuid[])
`

type RemoveCategoriesParams struct {
	ProgramID pgtype.UUID   `json:"program_id"`
	Column2   []pgtype.UUID `json:"column_2"`
}

func (q *Queries) RemoveCategories(ctx context.Context, arg RemoveCategoriesParams) error {
	_, err := q.db.Exec(ctx, removeCategories, arg.ProgramID, arg.Column2)
	return err
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE programs
SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  type = COALESCE($4, type),
  language = COALESCE($5, language),
  duration_ms = COALESCE($6, duration_ms),
  updated_at = NOW(),
  updated_by = $7
WHERE id = $1
RETURNING id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by
`

type UpdateProgramParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Language    string      `json:"language"`
	DurationMs  int32       `json:"duration_ms"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.DurationMs,
		arg.UpdatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.SourceID,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}
