// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProgram = `-- name: CreateProgram :one
INSERT INTO programs (slug, title, description, type, language, duration_ms, tags, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, title, description, type, language, duration_ms, tags, created_at, updated_at, published_at, deleted_at, created_by, published_by, updated_by, deleted_by
`

type CreateProgramParams struct {
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Language    string      `json:"language"`
	DurationMs  int32       `json:"duration_ms"`
	Tags        []string    `json:"tags"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.DurationMs,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const deleteProgram = `-- name: DeleteProgram :exec
UPDATE programs
SET deleted_at = NOW(), deleted_by = $2
WHERE id = $1
`

type DeleteProgramParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteProgram(ctx context.Context, arg DeleteProgramParams) error {
	_, err := q.db.Exec(ctx, deleteProgram, arg.ID, arg.DeletedBy)
	return err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, slug, title, description, type, language, duration_ms, tags, created_at, updated_at, published_at, deleted_at, created_by, published_by, updated_by, deleted_by FROM programs WHERE id = $1
`

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, slug, title, description, type, language, duration_ms, tags, created_at, updated_at, published_at, deleted_at, created_by, published_by, updated_by, deleted_by FROM programs WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListProgramsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Language,
			&i.DurationMs,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.PublishedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishProgram = `-- name: PublishProgram :one
UPDATE programs
SET published_at = NOW(), published_by = $2
WHERE id = $1
RETURNING id, slug, title, description, type, language, duration_ms, tags, created_at, updated_at, published_at, deleted_at, created_by, published_by, updated_by, deleted_by
`

type PublishProgramParams struct {
	ID          pgtype.UUID `json:"id"`
	PublishedBy pgtype.UUID `json:"published_by"`
}

func (q *Queries) PublishProgram(ctx context.Context, arg PublishProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, publishProgram, arg.ID, arg.PublishedBy)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE programs
SET
  title = COALESCE($2, title),
  description = COALESCE($3, description),
  type = COALESCE($4, type),
  language = COALESCE($5, language),
  duration_ms = COALESCE($6, duration_ms),
  tags = COALESCE($7, tags),
  updated_at = NOW(),
  updated_by = $8
WHERE id = $1
RETURNING id, slug, title, description, type, language, duration_ms, tags, created_at, updated_at, published_at, deleted_at, created_by, published_by, updated_by, deleted_by
`

type UpdateProgramParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Language    string      `json:"language"`
	DurationMs  int32       `json:"duration_ms"`
	Tags        []string    `json:"tags"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Language,
		arg.DurationMs,
		arg.Tags,
		arg.UpdatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}
