// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (type, metadata)
VALUES ($1, $2)
RETURNING id, type, metadata
`

type CreateSourceParams struct {
	Type     string `json:"type"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource, arg.Type, arg.Metadata)
	var i Source
	err := row.Scan(&i.ID, &i.Type, &i.Metadata)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, type, metadata FROM sources WHERE id = $1
`

func (q *Queries) GetSourceByID(ctx context.Context, id pgtype.UUID) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(&i.ID, &i.Type, &i.Metadata)
	return i, err
}
