// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, slug, title, description, type, language, duration_ms, created_at, updated_at, published_at, deleted_at, source_id, created_by, published_by, updated_by, deleted_by FROM programs WHERE id = $1
`

func (q *Queries) GetProgramByID(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Language,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.SourceID,
		&i.CreatedBy,
		&i.PublishedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const getProgramCategories = `-- name: GetProgramCategories :many
SELECT c.id, c.name, c.description FROM categories c
JOIN categorized_as ca ON c.id = ca.category_id
WHERE ca.program_id = $1
`

func (q *Queries) GetProgramCategories(ctx context.Context, programID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getProgramCategories, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
