// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, type, payload, enqueued, created_at, program_id FROM outbox_events
WHERE enqueued = false
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Enqueued,
			&i.CreatedAt,
			&i.ProgramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventEnqueued = `-- name: MarkOutboxEventEnqueued :exec
UPDATE outbox_events
SET enqueued = true
WHERE id = $1
`

func (q *Queries) MarkOutboxEventEnqueued(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventEnqueued, id)
	return err
}
