// Package discovery_api Code generated by swaggo/swag. DO NOT EDIT
package discovery_api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/programs": {
            "get": {
                "description": "Search programs with filters and pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "programs"
                ],
                "summary": "Search programs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "podcast",
                            "documentary"
                        ],
                        "type": "string",
                        "description": "Filter by type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ar",
                            "en"
                        ],
                        "type": "string",
                        "description": "Filter by language",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "published_at_desc",
                            "published_at_asc",
                            "relevance"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by tags (comma-separated)",
                        "name": "tags",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_discovery_handler.SearchProgramsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/programs/facets": {
            "get": {
                "description": "Get available facets (types, languages, tags) for filtering programs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "programs"
                ],
                "summary": "Get facets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_discovery_handler.FacetsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/programs/recent": {
            "get": {
                "description": "Get recently published programs with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "programs"
                ],
                "summary": "Get recent programs",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "podcast",
                            "documentary"
                        ],
                        "type": "string",
                        "description": "Filter by type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ar",
                            "en"
                        ],
                        "type": "string",
                        "description": "Filter by language",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_discovery_handler.RecentProgramsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/programs/{id}": {
            "get": {
                "description": "Get a specific published program by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "programs"
                ],
                "summary": "Get program",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Program ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_discovery_handler.ProgramResult"
                        }
                    },
                    "404": {
                        "description": "Program not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_discovery_handler.FacetsResponse": {
            "type": "object",
            "properties": {
                "facets": {
                    "$ref": "#/definitions/internal_discovery_handler.SearchFacets"
                }
            }
        },
        "internal_discovery_handler.ProgramResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "published_at": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_discovery_handler.RecentProgramsResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/internal_discovery_handler.SearchPagination"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_discovery_handler.ProgramResult"
                    }
                }
            }
        },
        "internal_discovery_handler.SearchFacets": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "type": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_discovery_handler.SearchPagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_discovery_handler.SearchProgramsResponse": {
            "type": "object",
            "properties": {
                "facets": {
                    "$ref": "#/definitions/internal_discovery_handler.SearchFacets"
                },
                "pagination": {
                    "$ref": "#/definitions/internal_discovery_handler.SearchPagination"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_discovery_handler.ProgramResult"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MediaCMS Discovery API",
	Description:      "Public search and discovery API for MediaCMS programs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
